### ISSUE TITLE
Unable to use workflow

### ISSUE THREAD

**Issue by UUAMike** [giovannicoppola/alfred-ICDbrowser#1]
I am not able to get this to work:

When I type 'icd-b' it seems like it will bring up the workflow, but then it it switches to wanting to conduct a google search.

When I try to use an assigned hotkey, it brings up the workflow, but typing in an ICD10 code doesn't do anything.

https://github.com/giovannicoppola/alfred-ICDbrowser/assets/29314039/ef65a12b-fa6b-4ab7-98eb-413769fc4b44

Here's the debug log:
[10:55:31.357] ERROR: alfred-ICDbrowser[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/michael/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.21C2131E-B879-4F86-8687-A5363E9E6D00/icd-query.py", line 10, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

EDIT: Fixed. No clue what this is about, but I installed pandas by running `pip3 install pandas` terminal

**Comment by giovannicoppola** [comment]
good catch! I forgot to add this dependency to the documentation, I will do so now. Let me know if I can help with anything else!
